FROM nginx:alpine

# Copy the pre-built Angular app from the GH Actions context
COPY dist/portofoliu-personal/browser /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
