FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/
COPY database/package*.json ./database/
COPY frontend/package*.json ./frontend/

RUN npm install

COPY . .

RUN cd database && npx prisma generate --schema prisma/schema.prisma

EXPOSE 3000

CMD ["sh", "-c", "cd /app/database && npx prisma migrate deploy --schema prisma/schema.prisma && npx ts-node --transpile-only seed.ts && cd /app/backend && npx ts-node --transpile-only index.ts"]
